---
coordinates:
  latitude: 40.75805
  longitude: 73.97941
hue:
  username: your_username
  light_ids:
    - 1
    - 2
    - 3
times:
  sunrise: will_calculate
  sunset: will_calculate
  timezone: America/Los_Angeles
